// Phase 0 spike 4 (TS side) — prove a targeted encrypted host snapshot, sealed by the
// e2ee package (see internal/e2ee/vector_test.go + testdata/snapshot-seed-vector.json),
// can be:
//   1. intercepted by the worker via its in-clear routing ID (handleHostFrame),
//   2. stripped of the 4-byte routing ID (relay header removal),
//   3. opened with the shared cipher (shared/e2ee.ts) — version at offset 1, AAD=[opcode],
//   4. seeded into a headless VT to produce a stable, SGR-free plain-text screen,
// with NO Go/TS wire change. This is the gate for `shell_screen` cold-start seeding.
//
// The fixture is a committed, deterministic crypto test vector (fixed nonce) owned by the
// e2ee package; `go test ./internal/e2ee/` compares the generated bytes against it and fails
// on drift. The test REQUIRES it: a missing fixture fails the gate, so the cross-language
// round-trip is exercised, not skipped.
import { describe, expect, it } from "vitest";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { BrowserFrameCipher } from "../shared/e2ee";
import { Terminal } from "@xterm/headless";

type VT = InstanceType<typeof Terminal>;

function hexToBytes(hex: string): Uint8Array<ArrayBuffer> {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i += 1) out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  return out;
}

async function writeAll(term: VT, data: Uint8Array): Promise<void> {
  await new Promise<void>((resolve) => term.write(data, resolve));
}

function visibleScreen(term: VT): string {
  const buf = term.buffer.active;
  const start = buf.viewportY;
  const lines: string[] = [];
  for (let i = 0; i < term.rows; i += 1) {
    const line = buf.getLine(start + i);
    lines.push(line ? line.translateToString(true) : "");
  }
  return lines.join("\n");
}

const here = path.dirname(fileURLToPath(import.meta.url));
// The fixture is owned by the e2ee package (package-local generation, fixed nonce); the TS
// spike reads it from there so Go and CI always test the same bytes.
const vectorPath = path.join(here, "../internal/e2ee/testdata/snapshot-seed-vector.json");

describe("Go-to-TypeScript encrypted snapshot seeding", () => {
  it("worker intercepts, strips targetId, opens with browser cipher, seeds a stable VT", async () => {
    if (!existsSync(vectorPath)) {
      throw new Error(`missing fixture ${vectorPath}; run \`go test ./internal/e2ee/ -update\``);
    }
    const vector = JSON.parse(readFileSync(vectorPath, "utf8")) as {
      keyHex: string;
      targetId: number;
      sealedHex: string;
      payloadHex: string;
      cols: number;
      rows: number;
    };
    const sealed = hexToBytes(vector.sealedHex);

    // 1. Worker reads the in-clear routing ID (offset 1, 4 bytes BE) — the interception key.
    expect(sealed[0]).toBe(0x03); // Snapshot opcode
    const targetId = new DataView(sealed.buffer, sealed.byteOffset, sealed.byteLength).getUint32(1);
    expect(targetId).toBe(vector.targetId);

    // 2. Strip the 4-byte routing ID (relay header removal) -> [0x03][ver][nonce][ct].
    const stripped = new Uint8Array(sealed.byteLength - 4);
    stripped[0] = 0x03;
    stripped.set(sealed.subarray(5), 1);

    // 3. Open with the browser cipher (version at offset 1, AAD=[opcode]).
    const cipher = await BrowserFrameCipher.fromKey(hexToBytes(vector.keyHex));
    const opened = await cipher.open(stripped);
    expect(opened[0]).toBe(0x03);
    const payload = new Uint8Array(opened.subarray(1));
    expect(Buffer.from(payload).toString("hex")).toBe(vector.payloadHex);

    // 4. Seed the headless VT and assert a stable, SGR-free plain-text screen.
    const term = new Terminal({ allowProposedApi: true, cols: vector.cols, rows: vector.rows });
    await writeAll(term, payload);
    const screen = visibleScreen(term);
    expect(screen).toContain("calin@host:~/repo$ npm test");
    expect(screen).toContain("12 tests passed");
    expect(screen).not.toContain("\x1b[");
    term.dispose();
  });
});
