package e2ee

import (
	"bytes"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"flag"
	"os"
	"path/filepath"
	"testing"
)

// updateVector rewrites the checked-in cross-language fixture from the generated bytes.
// Run `go test ./internal/e2ee/ -update` only after a deliberate e2ee change.
var updateVector = flag.Bool("update", false, "rewrite testdata/snapshot-seed-vector.json")

const vectorPath = "testdata/snapshot-seed-vector.json"

// TestSnapshotSeedVector pins the Go side of the cross-language snapshot-seed fixture. It
// seals a targeted host snapshot with a FIXED nonce (deterministic) and compares the result
// byte-for-byte against the checked-in vector, failing on drift so the Go and TS CI jobs
// always test the same bytes (the TS spike reads the same fixture). Deterministic generation
// stays package-local: SealFrame still uses a random nonce for live traffic (nonce uniqueness
// per key), so this fixed nonce is only for the committed input->output vector.
func TestSnapshotSeedVector(t *testing.T) {
	key := make([]byte, KeyBytes)
	for i := range key {
		key[i] = byte(i + 1)
	}
	cipher, err := New(key)
	if err != nil {
		t.Fatal(err)
	}
	// Pin the v2 sender stream as well as the nonce for deterministic cross-language bytes.
	copy(cipher.sendStream[:], []byte{1, 2, 3, 4, 5, 6, 7, 8})

	const targetID = 0x01020304 // an internal (non-viewer) routing id
	payload := []byte("\x1b[1;32mcalin@host\x1b[0m:\x1b[34m~/repo\x1b[0m$ npm test\r\n  \x1b[32m✓\x1b[0m 12 tests passed (450ms)\r\n\x1b[1;32mcalin@host\x1b[0m:\x1b[34m~/repo\x1b[0m$ ")

	frame := make([]byte, 5+len(payload))
	frame[0] = 0x03 // protocol.Snapshot
	binary.BigEndian.PutUint32(frame[1:5], targetID)
	copy(frame[5:], payload)

	nonce := make([]byte, NonceBytes)
	for i := range nonce {
		nonce[i] = byte(0x40 + i)
	}
	sealed, err := cipher.sealFrameWithNonce(frame, nonce)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(sealed[:5], frame[:5]) {
		t.Fatal("target routing header was not kept in the clear")
	}

	vector := map[string]any{
		"keyHex":     hex.EncodeToString(key),
		"targetId":   targetID,
		"sealedHex":  hex.EncodeToString(sealed),
		"payloadHex": hex.EncodeToString(payload),
		"cols":       120,
		"rows":       36,
	}
	data, err := json.Marshal(vector)
	if err != nil {
		t.Fatal(err)
	}

	if *updateVector {
		if err := os.MkdirAll(filepath.Dir(vectorPath), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(vectorPath, data, 0o644); err != nil {
			t.Fatal(err)
		}
		t.Logf("wrote %s", vectorPath)
		return
	}

	committed, err := os.ReadFile(vectorPath)
	if err != nil {
		t.Fatalf("read %s: %v (run with -update to create it)", vectorPath, err)
	}
	if !bytes.Equal(committed, data) {
		t.Fatalf("vector drift: generated bytes differ from %s; run `go test ./internal/e2ee/ -update` after a deliberate e2ee change", vectorPath)
	}
}
