package protocol

import "encoding/binary"

const (
	Output            byte = 0x01
	Input             byte = 0x02
	Snapshot          byte = 0x03
	Resize            byte = 0x04
	FinalSnapshot     byte = 0x05
	Ping              byte = 0x06
	Pong              byte = 0x07
	BroadcastSnapshot byte = 0x08
	ConfirmedEOF      byte = 0x09
	FileRequest       byte = 0x0a
	FileResponse      byte = 0x0b
	// Send is a DO->host control frame carrying one atomic shell_send operation: an
	// operation id, an enter flag, a 16-byte dispatch token (opaque to the host), and the
	// text. The host writes text (plus a single \r when enter is set) to the PTY in one
	// write and acknowledges with SendAck, echoing the dispatch token verbatim.
	Send byte = 0x0c
	// SendAck is a host->DO acknowledgement for a Send frame, echoing the operation id, the
	// dispatch token verbatim, and a result code. It is only sent after the complete
	// operation has been written.
	SendAck byte = 0x0d
	// AgentEvent is a host->viewer frame carrying the conversation an agent has
	// recorded, as JSON. It travels sealed with the same frame cipher as Output,
	// so a relay forwards it without being able to read it. See internal/agentlog:
	// a full-screen agent's conversation cannot be recovered from its screen, and
	// every agent keeps a machine-readable record of it on the host instead.
	AgentEvent byte = 0x0e
)

// Send result codes carried in a SendAck frame.
const (
	SendResultDelivered byte = 0x00 // the complete operation (text + optional \r) reached the PTY
	SendResultUncertain byte = 0x01 // the write was partial/interrupted; the operation is not confirmed
)

const (
	// SendOperationIDBytes is the fixed width of the operation id (a UUID v4, 36 ASCII bytes).
	SendOperationIDBytes = 36
	// SendDispatchTokenBytes is the fixed width of the dispatch token: an opaque nonce
	// generated by the DO. The host echoes it verbatim in the SendAck so the DO can
	// correlate an ack with a specific send attempt even when operation ids are reused.
	SendDispatchTokenBytes = 16
	// SendMaxTextBytes bounds the text payload of a Send frame (matches the shell_send schema).
	SendMaxTextBytes = 8192
)

func Frame(opcode byte, payload []byte) []byte {
	frame := make([]byte, len(payload)+1)
	frame[0] = opcode
	copy(frame[1:], payload)
	return frame
}

// EncodeSend builds a Send frame (DO -> host): [Send][operationID(36)][enter(1)][dispatchToken(16)][text...].
// The dispatch token must be exactly SendDispatchTokenBytes; the text must be
// 1..SendMaxTextBytes, the caller being responsible for having validated it.
func EncodeSend(operationID string, enter bool, dispatchToken []byte, text []byte) []byte {
	if len(dispatchToken) != SendDispatchTokenBytes {
		panic("protocol: EncodeSend dispatch token must be 16 bytes")
	}
	enterByte := byte(0)
	if enter {
		enterByte = 1
	}
	payload := make([]byte, 0, SendOperationIDBytes+1+SendDispatchTokenBytes+len(text))
	payload = append(payload, operationID[:SendOperationIDBytes]...)
	payload = append(payload, enterByte)
	payload = append(payload, dispatchToken...)
	payload = append(payload, text...)
	return Frame(Send, payload)
}

// DecodeSend parses a Send frame. It returns ok=false on a malformed frame: wrong opcode, a
// short frame (including a dispatch token shorter than SendDispatchTokenBytes), or a text
// payload outside 1..SendMaxTextBytes.
func DecodeSend(frame []byte) (operationID string, enter bool, dispatchToken []byte, text []byte, ok bool) {
	if len(frame) < 1+SendOperationIDBytes+1+SendDispatchTokenBytes+1 || frame[0] != Send {
		return "", false, nil, nil, false
	}
	payload := frame[1:]
	operationID = string(payload[:SendOperationIDBytes])
	enter = payload[SendOperationIDBytes] == 1
	tokenStart := SendOperationIDBytes + 1
	dispatchToken = append([]byte(nil), payload[tokenStart:tokenStart+SendDispatchTokenBytes]...)
	text = payload[tokenStart+SendDispatchTokenBytes:]
	if len(text) < 1 || len(text) > SendMaxTextBytes {
		return "", false, nil, nil, false
	}
	return operationID, enter, dispatchToken, text, true
}

// EncodeSendAck builds a SendAck frame (host -> DO): [SendAck][operationID(36)][dispatchToken(16)][result(1)].
// The dispatch token is the DO's token echoed verbatim (the host never generates or
// interprets it).
func EncodeSendAck(operationID string, dispatchToken []byte, result byte) []byte {
	if len(dispatchToken) != SendDispatchTokenBytes {
		panic("protocol: EncodeSendAck dispatch token must be 16 bytes")
	}
	payload := make([]byte, 0, SendOperationIDBytes+SendDispatchTokenBytes+1)
	payload = append(payload, operationID[:SendOperationIDBytes]...)
	payload = append(payload, dispatchToken...)
	payload = append(payload, result)
	return Frame(SendAck, payload)
}

// DecodeSendAck parses a SendAck frame. It returns ok=false on a malformed frame: wrong
// opcode or a total length other than exactly 1+36+16+1 (including a dispatch token not
// exactly SendDispatchTokenBytes).
func DecodeSendAck(frame []byte) (operationID string, dispatchToken []byte, result byte, ok bool) {
	if len(frame) != 1+SendOperationIDBytes+SendDispatchTokenBytes+1 || frame[0] != SendAck {
		return "", nil, 0, false
	}
	payload := frame[1:]
	tokenStart := SendOperationIDBytes
	dispatchToken = append([]byte(nil), payload[tokenStart:tokenStart+SendDispatchTokenBytes]...)
	return string(payload[:SendOperationIDBytes]), dispatchToken, payload[tokenStart+SendDispatchTokenBytes], true
}

func DecodeResize(frame []byte) (cols, rows uint16, ok bool) {
	if len(frame) != 5 || frame[0] != Resize {
		return 0, 0, false
	}
	cols = binary.BigEndian.Uint16(frame[1:3])
	rows = binary.BigEndian.Uint16(frame[3:5])
	if cols < 10 || cols > 500 || rows < 4 || rows > 300 {
		return 0, 0, false
	}
	return cols, rows, true
}
